language: python
branches:
  only:
  - main
jobs:
  include:
  - stage: build
    script: bash scripts/zip_archive.sh
    workspaces:
      create:
        name: backend_auction
        paths:
        - devops/backend_auction.zip
  - stage: deploy
    install:
    - pip3 install ansible
    script: scripts/ansible.sh
    workspaces:
      use: backend_auction
    before_install:
    - openssl aes-256-cbc -K $encrypted_12f6baf5be1e_key -iv $encrypted_12f6baf5be1e_iv
      -in AmazoniTechArt.pem.enc -out AmazoniTechArt.pem -d
    - cd devops && openssl aes-256-cbc -K $encrypted_3c84dcdc6bbe_key -iv $encrypted_3c84dcdc6bbe_iv
      -in .env.enc -out .env -d && cd ..
