AUCTION_DB_NAME: postgres
AUCTION_DB_USER: postgres
AUCTION_DB_PASSWORD: postgres
AUCTION_DB_HOST: auction-db.cv7h10ow1qcw.eu-central-1.rds.amazonaws.com
AUCTION_DB_PORT: 5432
AUCTION_BROKER_PORT: 6379
AUCTION_CELERY_BROKER_URL: redis
AUCTION_CELERY_RESULT_BACKEND: resis
EMAIL_HOST: smtp.gmail.com
EMAIL_HOST_USER: testsoven@gmail.com
EMAIL_HOST_PASSWORD: 12345687!
EMAIL_PORT: 587
EMAIL_USE_TLS: True
AUCTION_REDIS_PORT: 6379
AUCTION_REDIS_HOST: redis
LOG_LEVEL: INFO
ALLOWED_HOSTS: ec2-3-122-178-66.eu-central-1.compute.amazonaws.com
SECRET_KEY: django-insecure-o&y*mc(mc4ya8c(196ne(mc(ar-qko1ac!l+267=z8fp$f_ka=
ROOT_LOG_LEVEL: INFO