# Generated by Django 3.2 on 2021-04-27 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='current price, $')),
                ('opening_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='opening price, $')),
                ('opening_date', models.DateField(verbose_name='opening date')),
                ('closing_date', models.DateField(verbose_name='closing date')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('IN_PROGRESS', 'IN_PROGRESS'), ('CLOSED', 'CLOSED')], max_length=15, verbose_name='status')),
                ('object_id', models.IntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='item.item')),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auction.auction')),
            ],
        ),
    ]
