# Generated by Django 3.2 on 2021-05-06 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dutch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='end price, $')),
                ('frequency', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='English',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_it_now', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='buy it now price, $')),
                ('reverse_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='reverse price, $')),
            ],
        ),
        migrations.AlterField(
            model_name='auction',
            name='closing_date',
            field=models.DateTimeField(verbose_name='closing date'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='opening_date',
            field=models.DateTimeField(verbose_name='opening date'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'In Progress'), (3, 'Closed')]),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price, $')),
                ('timestamp', models.DateField(auto_now=True, verbose_name='timestamp')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot', to='auction.lot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
