# Generated by Django 3.2 on 2021-04-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dutch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='end price, $')),
                ('frequency', models.DateTimeField(verbose_name='frequency')),
            ],
        ),
        migrations.CreateModel(
            name='English',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_it_now', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='opening price, $')),
                ('reverse_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='opening price, $')),
            ],
        ),
    ]
