# Generated by Django 3.2 on 2021-05-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='timestamp',
            field=models.DateField(auto_now=True, verbose_name='timestamp'),
        ),
    ]
