- name: collect static
  shell: cd {{project_homedir}} && export $(grep -v '^#' .env | xargs) && sudo chown -R $USER /home/ && poetry run python manage.py collectstatic --noinput
  become_user: "{{ansible_user}}"

- name: move static folder
  shell: sudo mkdir -p /opt/backend_auction/ && sudo mv -n {{project_homedir}}/static/ /opt/backend_auction/

- name: restart gunicorn
  service:
    name: gunicorn
    state: restarted
    enabled: yes

- name: restart daphne
  service:
    name: daphne
    state: restarted
    enabled: yes

- name: restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
